# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jonahkollner <jonahkollner@student.42.f    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2023/09/08 09:50:40 by jkollner          #+#    #+#              #
#    Updated: 2023/10/14 15:40:41 by jonahkollne      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

name = irc
cc = c++
cflags = -Wall -Werror -Wextra -std=c++98
src = main.cpp Server.cpp User.cpp Chat.cpp Executer.cpp Commander.cpp
obj = ${src:.cpp=.o}

all: ${name}

${name}: ${obj}
	${cc} ${cflags} ${obj} -o ${name}

clean:
	rm ${obj}

fclean: clean
	rm ${name}

re:	fclean all

.PHONY: all ${name} clean fclean
